//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _16_Image_CRUD_App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class employee
    {
        public int id { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Employee Name")]
        public string name { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Employee Designation")]
        public string designation { get; set; }


        // Stores uploaded image file path
        [DisplayName("Employee Image")]
        public string image_path { get; set; }

        // HttpPostedFileBase Property required to save the uploaded image

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
