//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18_Signup_Login_Page.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("User ID")]
        public int Id { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DisplayName("FirstName")]
        public string firstname { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DisplayName("LastName")]
        public string lastname { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Gender")]
        public string gender { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Age")]
        public int age { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Email")]
//        [RegularExpression(@"^[^@\s]+@[^@\s]+\.[^@\s]+$
//", ErrorMessage="Please enter a valid email")]
        public string email { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Username")]
        public string username { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Password")]
        [DataType(DataType.Password)]   
        public string password { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Confirm Password")]
        [DataType(DataType.Password)]
        // Annotation to compare the field with password
        [Compare("password", ErrorMessage = "Passwords does not match")]
        public string confirmpassword { get; set; }
    }
}
