//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _13_Shortcut_CRUD_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public int id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public Nullable<int> age { get; set; }
        public string designation { get; set; }
    }
}
