//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10_Login_Form_using_Session_and_EF.Models
{
    using System;
    using System.Collections.Generic;
    using System.Security.Cryptography;
    using System.Web.UI.WebControls;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class LoginTableDB
    {
        public int id { get; set; }

        // To Display as Username in then form
        [DisplayName("Username")]
        [Required(ErrorMessage ="UserName is required")]
        public string username { get; set; }


        // To Display as Password  in then form
        [DisplayName("Password")]
        // Marking Datatype as Password so that EditorFor stores as Bullet points
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password is required")]
        public string password { get; set; }
    }
}
